select * from customer limit 5;

# What is the total revenue generated by male vs female customers ?
select gender,sum(purchase_amount) total_revenue from customer group by gender;

# Which customers used a discount but still spent more than the average purchase amt ?
select customer_id,purchase_amount from customer where discount_applied ="Yes" and purchase_amount>(select avg(purchase_amount) from customer) ;
select gender,count(customer_id) from customer where discount_applied ="Yes" and purchase_amount>(select avg(purchase_amount) from customer) group by gender ;

#  Which are the top 5 products with highest average review rating ?
select item_purchased as product , round(avg(review_rating),2) from customer group by item_purchased  order by avg(review_rating) desc limit 5;

# compare the average purchase amnts b/w standard & Express shipping 
select shipping_type , avg(purchase_amount) from customer where shipping_type in ('Express','Standard') group by shipping_type;

# do subscribe customers spend more ? compare average spend & total revenue b/w subscribers and non-subscribers
select subscription_status ,count(customer_id) total_customer ,avg(purchase_amount) average_spend ,sum(purchase_amount) total_revenue 
from customer group by subscription_status;

# which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased,sum(case when discount_applied='Yes' then 1 else 0 end )/count(*)*100 as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#  Segment customers into new,reeturning,loyal based on their total no. of previous purchases & show the count of each segment
select  t.customer_type ,count(t.customer_id)
from (select customer_id ,case when previous_purchases=1 then "new"
			        when previous_purchases between 2 and 10 then "returning"
                    else "loyal"
                    end as customer_type
	  from customer ) as t 
group by t.customer_type ;

#  What are the top 3 most puchased products within each category?
with view as (select category , item_purchased , row_number() over(partition by category order by count(customer_id) desc) ranking
from customer
group by category ,item_purchased)
select category , item_purchased ,ranking
from view 
where ranking <=3;

#  Are customers who are repeat buyers(more than 5 previous purchases) also  likely to subscribe ?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

#  What are the revenue contribution of each age group ?
select age_grp ,sum(purchase_amount) as revenue
from customer
group by age_grp
order by revenue desc;